-- Recreate participants table with correct schema (without foreign key constraints for location tables)
CREATE TABLE participants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  first_name text NOT NULL,
  last_name text NOT NULL,
  country text NOT NULL,
  district text NOT NULL,
  sub_county text NOT NULL,
  parish text NOT NULL,
  village text NOT NULL,
  -- Location IDs for better data integrity (nullable, no foreign keys for now)
  country_id uuid,
  district_id uuid,
  subcounty_id uuid,
  parish_id uuid,
  village_id uuid,
  sex text NOT NULL,
  age integer,
  date_of_birth timestamp,
  is_pwd text NOT NULL DEFAULT 'no',
  disability_type text,
  is_mother text NOT NULL DEFAULT 'no',
  is_refugee text NOT NULL DEFAULT 'no',
  designation text NOT NULL,
  enterprise text NOT NULL,
  contact text NOT NULL,
  is_permanent_resident text NOT NULL DEFAULT 'no',
  are_parents_alive text NOT NULL DEFAULT 'no',
  number_of_children integer NOT NULL DEFAULT 0,
  employment_status text NOT NULL DEFAULT 'unemployed',
  monthly_income integer NOT NULL DEFAULT 0,
  -- Employment tracking fields
  wage_employment_status text,
  wage_employment_sector text,
  wage_employment_scale text,
  self_employment_status text,
  self_employment_sector text,
  business_scale text,
  secondary_employment_status text,
  secondary_employment_sector text,
  secondary_business_scale text,
  -- Financial inclusion fields
  accessed_loans text NOT NULL DEFAULT 'no',
  individual_saving text NOT NULL DEFAULT 'no',
  group_saving text NOT NULL DEFAULT 'no',
  -- Location classification
  location_setting text,
  -- Personal Information
  marital_status text,
  education_level text,
  source_of_income text,
  nationality text NOT NULL DEFAULT 'Ugandan',
  population_segment text,
  refugee_location text,
  is_active_student text NOT NULL DEFAULT 'no',
  -- VSLA Information
  is_subscribed_to_vsla text NOT NULL DEFAULT 'no',
  vsla_name text,
  -- Teen Mother
  is_teen_mother text NOT NULL DEFAULT 'no',
  -- Enterprise Information
  owns_enterprise text NOT NULL DEFAULT 'no',
  enterprise_name text,
  enterprise_sector text,
  enterprise_size text,
  enterprise_youth_male integer NOT NULL DEFAULT 0,
  enterprise_youth_female integer NOT NULL DEFAULT 0,
  enterprise_adults integer NOT NULL DEFAULT 0,
  -- Skills Information - as text arrays
  has_vocational_skills text NOT NULL DEFAULT 'no',
  vocational_skills_participations text[] DEFAULT '{}',
  vocational_skills_completions text[] DEFAULT '{}',
  vocational_skills_certifications text[] DEFAULT '{}',
  has_soft_skills text NOT NULL DEFAULT 'no',
  soft_skills_participations text[] DEFAULT '{}',
  soft_skills_completions text[] DEFAULT '{}',
  soft_skills_certifications text[] DEFAULT '{}',
  has_business_skills text NOT NULL DEFAULT 'no',
  -- Employment Details
  employment_type text,
  employment_sector text,
  -- Foreign keys (these tables should exist)
  project_id uuid NOT NULL,
  cluster_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  -- Activity tracking
  no_of_trainings integer NOT NULL DEFAULT 0,
  is_active text NOT NULL DEFAULT 'yes',
  main_challenge text,
  skill_of_interest text,
  expected_impact text,
  is_willing_to_participate text NOT NULL DEFAULT 'yes',
  -- Timestamps
  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now()
);