export { default as NewLandingPage } from "./page";
export { Header } from "./components/Header";
export { HeroSection } from "./components/HeroSection";
export { FeaturesSection } from "./components/FeaturesSection";
export { FeatureCard } from "./components/FeatureCard";
export { TestimonialsSection } from "./components/TestimonialsSection";
export { DetailedFeaturesSection } from "./components/DetailedFeaturesSection";
export { PricingSection } from "./components/PricingSection";
export { FAQSection } from "./components/FAQSection";
export { ContactSection } from "./components/ContactSection";
export { CTASection } from "./components/CTASection";
export { Footer } from "./components/Footer";
